/** Members roster, to be updated each semester. Used in the members page. */
export const members = [
    {
        name: "Seth Kinoshita",
        voicePart: "Baritone",
        perc: true,
        position: "Co-Music Director",
        semJoined: "Fall '23",
        imagePath: "/members/seth.jpeg",
        bio: "Seth Kinoshita is a 4th year biochemistry major who has been in SympVibes since Fall 2023. Outside of singing, he has playing the violin for 9 years (he thinks the cello is cooler though). Fun fact - he likes to eat kiwis with the skin on!",
    },
    {
        name: "Nicholas Oselette",
        voicePart: "Tenor",
        perc: false,
        position: "Co-Music Director",
        semJoined: "Fall '23",
        imagePath: "/members/ose.jpg",
        bio: "Nicholas is a 1st year masters student in Solid Earth & Planetary Science. He also writes music, sings and produces and has been doing so since the 8th grade.",
    },
    {
        name: "Wesley Lanter",
        voicePart: "Bass",
        perc: false,
        position: "Business Manager",
        semJoined: "Fall '22",
        imagePath: "/members/wesley.png",
        bio: "Wesley is a 4th year biology and ALIS double major from Canton, GA. Outside of SV, Wesley enjoys playing with frogs in the Nie Lab, listening to reggaeton & Dutch dance pop, and battling the line at Chipotle (he lost the battle).",
    },
    {
        name: "Facundo Pagani",
        voicePart: "Tenor",
        perc: true,
        position: undefined,
        semJoined: "Fall '23",
        imagePath: "/members/fakundao.png",
        bio: "His name is actually Fakundao. He also hates coming to practice.",
    },
    {
        name: "Will Goldsmith",
        voicePart: "Bass",
        perc: true,
        position: "Secretary",
        semJoined: "Fall '23",
        imagePath: "/members/will.jpg",
        bio: "Will, better known as Goldsmith or Goldy, is a 4th year Industrial Engineering major from Decatur, GA. You can find Will roaming the streets of Atlanta, murmuring under his breath or singing at the top of his lungs. But we promise he's just a chill guy.",
    },
    {
        name: "Sam Kim",
        voicePart: "Tenor",
        perc: true,
        position: undefined,
        semJoined: "Spring '24",
        imagePath: "/members/sam.jpeg",
        bio: "Sam is a 4th year double major in Computer Science and Math. In his spare time, he loves to work out (big man), cook (in and out of the kitchen), and take pictures.",
    },
    {
        name: "Ben Bond",
        voicePart: "Baritone",
        perc: false,
        position: undefined,
        semJoined: "Fall '24",
        imagePath: "/members/ben.jpeg",
        bio: "Ben is a masters aerospace engineering student from Athens, GA, though he'd rather be called a first-year master’s student. He likes lifting, computers, and anything with an engine. Feel free to distract him from his grad program (please don't)!",
    },
    {
        name: "Carter Strickland",
        voicePart: "Bass",
        perc: true,
        position: undefined,
        semJoined: "Fall '24",
        imagePath: "/members/carter.jpeg",
        bio: "Howdy! Carter is pursuing a Bachelors in Mechanical Engineering that he can’t wait to bring back to his hometown, Hortense, GA! He is all about meeting new folks, praising the Lord, and throwing down, so hit him up if you’re on campus (or not)!",
    },
];
