/** Members roster, to be updated each semester. Used in the members page. */
export const members = [
    {
        name: "Reetesh Sudhakar",
        voicePart: "Tenor",
        perc: true,
        position: "Webmaster",
        semJoined: "Spring '23",
        imagePath: "/members/ree.jpg",
        bio: "Ree is a 4th year Computer Science student from Portland, OR. He's been involved in music his entire life, with Indian music & percussion, choirs, and a cappella groups. He would love it if you showed him a picture of your dog. He loves dogs.",
    },
    {
        name: "Wesley Lanter",
        voicePart: "Bass",
        perc: false,
        position: "Business Manager",
        semJoined: "Fall '22",
        imagePath: "/members/wesley.png",
        bio: "Wesley is a 3rd year biology and ALIS double major from Canton, GA. Outside of SV, Wesley enjoys playing with frogs in the Nie Lab, listening to reggaeton & Dutch dance pop, and battling the line at Chipotle (he lost the battle).",
    },
    {
        name: "Daryn Roberts",
        voicePart: "Tenor",
        perc: true,
        position: "Music Director",
        semJoined: "Fall '22",
        imagePath: "/members/daryn.jpeg",
        bio: "What’s up team. My name is Daryn Roberts and I’m a 4th year Biomedical engineering major. My big dark secret is that I’m actually a huge nerd and I’m obsessed with Dungeons and Dragons.",
    },
    {
        name: "Evan Smallwood",
        voicePart: "Tenor",
        perc: false,
        position: undefined,
        semJoined: "Fall '22",
        imagePath: "/members/evan.jpg",
        bio: "Bio coming soon!.",
    },
    {
        name: "Facundo Pagani",
        voicePart: "Tenor",
        perc: false,
        position: undefined,
        semJoined: "Fall '23",
        imagePath: "/members/fakundao.png",
        bio: "His name is actually Fakundao.",
    },
    {
        name: "Seth Kinoshita",
        voicePart: "Baritone",
        perc: false,
        position: undefined,
        semJoined: "Fall '23",
        imagePath: "/members/seth.jpeg",
        bio: "Seth Kinoshita is a third-year biochemistry major who has been in SympVibes since Fall 2023. Outside of singing, he has playing the violin for 9 years (he thinks the cello is cooler though). Fun fact - he likes to eat kiwis with the skin on!",
    },
    {
        name: "Nicholas Oselette",
        voicePart: "Tenor",
        perc: false,
        position: undefined,
        semJoined: "Fall '23",
        imagePath: "/members/ose.jpg",
        bio: "Nicholas is a 4th year double major in Solid Earth & Planetary Science and Applied Language & Intercultural Studies. He also writes music, sings and produces and has been doing so since the 8th grade.",
    },
    {
        name: "Will Goldsmith",
        voicePart: "Bass",
        perc: true,
        position: undefined,
        semJoined: "Fall '23",
        imagePath: "/members/will.jpg",
        bio: "Will, better known as Goldsmith or Goldy, is a third year Industrial Engineering major from Decatur, GA. You can find Will roaming the streets of Atlanta, murmuring under his breath or singing at the top of his lungs. But we promise he's just a chill guy.",
    },
    {
        name: "Sam Kim",
        voicePart: "Tenor",
        perc: true,
        position: undefined,
        semJoined: "Spring '24",
        imagePath: "/members/sam.jpeg",
        bio: "Sam is a third year double major in Computer Science and Math. In his spare time, he loves to work out (big man), cook (in and out of the kitchen), and take pictures.",
    },
    {
        name: "Ben Bond",
        voicePart: "Baritone",
        perc: false,
        position: undefined,
        semJoined: "Fall '24",
        imagePath: "/members/ben.jpeg",
        bio: "Ben is a fifth year aerospace engineering student from Athens, GA, though he'd rather be called a first-year master’s student. He likes lifting, computers, and anything with an engine. Feel free to distract him from his grad program (please don't)!",
    },
    {
        name: "Donovan Sheppard",
        voicePart: "Baritone",
        perc: false,
        position: undefined,
        semJoined: "Fall '24",
        imagePath: "/members/donovan.jpeg",
        bio: "Donovan is a 4th year Math undergrad at GT. He enjoys running, reading, and playing poker in his free time. Donovan is a pilot select for the US Air Force, and he will go off to training next year ✈️.",
    },
    {
        name: "Carter Strickland",
        voicePart: "Bass",
        perc: true,
        position: undefined,
        semJoined: "Fall '24",
        imagePath: "/members/carter.jpeg",
        bio: "Howdy! Carter is pursuing a Bachelors in Mechanical Engineering that he can’t wait to bring back to his hometown, Hortense, GA! He is all about meeting new folks, praising the Lord, and throwing down, so hit him up if you’re on campus (or not)!",
    },
];
